DROP DATABASE IF EXISTS wordlebot;
DROP DATABASE IF EXISTS wordlebot;
CREATE DATABASE IF NOT EXISTS wordlebot;
USE wordlebot;

DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS guesses;
DROP TABLE IF EXISTS stats;

CREATE TABLE IF NOT EXISTS games(
  ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  userID VARCHAR(18) NOT NULL,
  gameID INT UNSIGNED NOT NULL
);
CREATE TABLE IF NOT EXISTS guesses(
  ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  userID VARCHAR(18) NOT NULL,
  guess CHAR(5) NOT NULL
);
CREATE TABLE IF NOT EXISTS stats(
  ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  userID VARCHAR(18) NOT NULL,
  guesses INT(1) NOT NULL,
  timestamp TIMESTAMP(1) DEFAULT CURRENT_TIMESTAMP(1)
);
CREATE TABLE IF NOT EXISTS rankings(
  ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  guildID VARCHAR(18) NOT NULL,
  userID VARCHAR(18) NOT NULL,
  started INT UNSIGNED,
  won INT UNSIGNED,
  finished INT UNSIGNED,
  numGuesses INT UNSIGNED
);